name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:

    strategy:
      matrix:
        node-version: [5.10.0, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Test
        run: npm run test
      - name: Check coding standards
        if: matrix.node-version == 22
        run: |
          pnpm i
          npm run lint
