name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build:

    strategy:
      matrix:
        node-version: [4.x, 6.x, 8.x, 10.x, 12.x, 14.x, 16.x, 18.x, 20.x, 22.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: npm run test
      - name: Check coding standards
        if: matrix.node-version == '22.x'
        run: npm run lint
