name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:

    strategy:
      matrix:
        node-version: [24]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - name: Cache node versions for nve
        id: cache-nve
        uses: actions/cache@v4
        with:
          path: ~/.cache/nve
          key: ${{ runner.os }}-nve
      - name: Test
        run: npm run test:all
      - name: Check coding standards
        run: npm run lint
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
